@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
{
  "name": "Romario",
  "email": "romario@email.com",
  "password": "123456"
}

###

# @name authenticate
POST  {{baseUrl}}/sessions
Content-Type: application/json
{
  "email": "romario@email.com",
  "password": "123456"
}

###

# @name create_question
POST  {{baseUrl}}/question
Content-Type: application/json
Authorization: Bearer {{authToken}}
{
  "email": "romario@email.com",
  "password": "123456"
}